# -*- coding: utf-8 -*-
"""index.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRIv5KJN0QqspwkctTbl4v8gO65Lj3ci
"""

import os
import base64
import json
import time
import google.generativeai as genai


genai.configure(api_key="AIzaSyB3IGoLBqChn18yk5eBL4grk8DRE7gP-Wc")

def upload_to_gemini(file_path):

    ext = os.path.splitext(file_path)[1].lower()
    mime = "application/pdf" if ext == ".pdf" else f"image/{ext.replace('.', '')}"

    file_ref = genai.upload_file(path=file_path, mime_type=mime)

    while file_ref.state.name == "PROCESSING":
        time.sleep(2)
        file_ref = genai.get_file(file_ref.name)
    return file_ref

def handler(event, context):

    print(" DiagnoSense Engine: Start processing...")

    try:
        if 'body' in event:
            body = json.loads(event['body']) if isinstance(event['body'], str) else event['body']
        else:
            body = event

        file_medical = body.get("medical_history_base64")
        file_lab = body.get("lab_report_base64")
        file_radiology = body.get("radiology_report_base64")

        if not any([file_medical, file_lab, file_radiology]):
            return {
                "statusCode": 400,
                "body": json.dumps({"message": "Please provide at least one medical document."})
            }

    except Exception as e:
        return {"statusCode": 400, "body": json.dumps({"message": f"Input Parsing Error: {str(e)}"})}

    tmp_map = {
        "medical_history": file_medical,
        "lab_report": file_lab,
        "radiology_report": file_radiology
    }

    try:
        gemini_files = []
        for key, b64_data in tmp_map.items():
            if b64_data and len(b64_data) > 100:
                path = f"/tmp/{key}.pdf"
                with open(path, "wb") as f:
                    f.write(base64.b64decode(b64_data))

                print(f" Processing {key}...")
                uploaded_file = upload_to_gemini(path)
                gemini_files.append(uploaded_file)

                if os.path.exists(path): os.remove(path)

        model = genai.GenerativeModel(
            model_name='gemini-2.5-flash',
            generation_config={
                "response_mime_type": "application/json",
                "temperature": 0.1
            }
        )

        prompt = """
        MEDICAL DATA ANALYSIS REQUEST
        Please analyze the medical information from the uploaded documents and provide structured JSON output:

        REQUIRED OUTPUT FORMAT (JSON):
        {{
          "high_priority_alerts": ["..."],
          "low_priority_alerts": ["..."],
          "current diagnoses": ["..."],
          "critical_allergies": ["..."],
          "ai-insight": [".."],
          "ai-summary":["....."],
          "likely_diagnoses": {{
            "high_likelihood": [{{"condition": "...", "probability": "XX%"}}],
            "possible": [{{"condition": "...", "probability": "XX%"}}],
            "low_likelihood": [{{"condition": "...", "probability": "XX%"}}]
          }}
        }}

        IMPORTANT: Only provide valid JSON output. Respond using 'English | عربي' for all text values.
        """

        print(" Performing Multi-Modal Clinical Fusion...")
        # إرسال البرومبت مع مراجع الملفات المتاحة
        response = model.generate_content([prompt, *gemini_files])

        # ز: تحويل النتيجة لـ JSON
        analysis_json = json.loads(response.text)

        # ح: إرجاع الرد النهائي المتوافق مع الـ Front-end والباك إند
        return {
            "statusCode": 200,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps(analysis_json, ensure_ascii=False)
        }

    except Exception as e:
        print(f" Critical Error: {str(e)}")
        return {
            "statusCode": 500,
            "body": json.dumps({"error": str(e)})
        }

